# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [
  ];
  boot.kernelModules = [
    "kvm-intel"
  ];
  boot.extraModulePackages = [
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/251630c4-9e38-4614-b8e7-7c6aef2bfc80";
    fsType = "btrfs";
    options = [
      "rw"
      "relatime"
      "ssd"
      "space_cache=v2"
      "subvol=@"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/575C-AFEC";
    fsType = "vfat";
    options = [
      "rw"
      "relatime"
      "fmask=0022"
      "dmask=0022"
      "codepage=437"
      "iocharset=ascii"
      "shortname=mixed"
      "utf8"
      "errors=remount-ro"
    ];
  };

  fileSystems."/mnt/cdrom" = {
    device = "/dev/sr0";
    fsType = "iso9660";
    options = [
      "ro"
      "noauto"
      "user"
      "unhide"
      "exec"
    ];
  };

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [
      "rw"
      "nosuid"
      "nodev"
      "noexec"
      "uid=1000"
      "gid=1000"
      "mode=0755"
      "size=40%"
      "inode64"
    ];
  };

  swapDevices = [
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
